# Generated by Django 5.1.4 on 2025-01-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
