# Generated by Django 5.1.4 on 2025-01-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
