# Generated by Django 5.0.6 on 2025-03-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
